services:
  - type: web
    name: production-management-backend
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend && npm run build --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_YxGjOeZawt39@ep-mute-forest-a1jh3m4f.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: production-erp-secret-key-2024
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
